kind: Service
apiVersion: v1
metadata:
  name: "monolith"
spec:
  selector:
    app: "monolith"
    secure: "enabled"
  ports:
    - protocol: "TCP"
      name: "https"
      port: 443
      targetPort: 443
      nodePort: 31000
    - protocol: "TCP"
      name: "http"
      port: 80
      targetPort: 80
  type: NodePort
